apiVersion: v1
kind: Service
metadata:
  name: companies-debezium
  namespace: companies
  labels:
    app: companies-debezium
spec:
  type: ClusterIP
  ports:
    - port: 8083
  selector:
    app: companies-debezium