// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package kafka_writer is a generated GoMock package.
package kafka_writer

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	kafka "github.com/segmentio/kafka-go"
)

// MockIKafkaWriter is a mock of IKafkaWriter interface.
type MockIKafkaWriter struct {
	ctrl     *gomock.Controller
	recorder *MockIKafkaWriterMockRecorder
}

// MockIKafkaWriterMockRecorder is the mock recorder for MockIKafkaWriter.
type MockIKafkaWriterMockRecorder struct {
	mock *MockIKafkaWriter
}

// NewMockIKafkaWriter creates a new mock instance.
func NewMockIKafkaWriter(ctrl *gomock.Controller) *MockIKafkaWriter {
	mock := &MockIKafkaWriter{ctrl: ctrl}
	mock.recorder = &MockIKafkaWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKafkaWriter) EXPECT() *MockIKafkaWriterMockRecorder {
	return m.recorder
}

// WriteMessages mocks base method.
func (m *MockIKafkaWriter) WriteMessages(ctx context.Context, msgs ...kafka.Message) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range msgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessages indicates an expected call of WriteMessages.
func (mr *MockIKafkaWriterMockRecorder) WriteMessages(ctx interface{}, msgs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, msgs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessages", reflect.TypeOf((*MockIKafkaWriter)(nil).WriteMessages), varargs...)
}
