apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
      tier: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
        tier: zookeeper
    spec:
      containers:
        - image: digitalwonderland/zookeeper
          name: zookeeper
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: zookeeper-config
          ports:
            - containerPort: 2181
              name: zookeeper