apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: companies
  labels:
    app: postgres
data:
  POSTGRES_DB: companies
  POSTGRES_USER: user
  POSTGRES_PASSWORD: pass
  VOLUME: /var/lib/postgresql/data