apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies-postgres
  labels:
    app: companies-postgres
spec:
  selector:
    matchLabels:
      app: companies-postgres
      tier: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: companies-postgres
        tier: postgres
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim