apiVersion: v1
kind: Service
metadata:
  name: companies-postgres
  labels:
    app: companies-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: companies-postgres
    tier: postgres