swagger: "2.0"
info:
  version: "1.0.0"
  title: "Companies-API"
basePath: "/v1"
tags:
  - name: "company"
schemes:
  - "http"
paths:
  /auth:
    post:
      tags:
        - "auth"
      summary: "Login"
      operationId: "login"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Login"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not found"
        "500":
          description: "Server error"
  /companies:
    post:
      tags:
        - "company"
      summary: "Add a new company"
      operationId: "createCompany"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "X-Forwarded-For"
          type: "string"
          required: true      
        - in: "header"
          name: "Authorization"
          type: "string"
          required: true
        - in: "body"
          name: "body"
          description: "Company object"
          required: true
          schema:
            $ref: "#/definitions/CreateCompanyRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Company"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not found"
        "500":
          description: "Server error"
    get:
      tags:
        - "company"
      summary: "Find companies"
      operationId: "getCompanies"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          required: true
        - name: "name"
          in: "query"
          type: "string"
        - name: "code"
          in: "query"
          type: "string"
        - name: "country"
          in: "query"
          type: "string"
        - name: "website"
          in: "query"
          type: "string"
        - name: "phone"
          in: "query"
          type: "string"
        - name: "page"
          in: "query"
          type: "string"
          default: 1
        - name: "limit"
          in: "query"
          type: "string"
          default: 10
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CompanyListResponse"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not found"
        "500":
          description: "Server error"

  /companies/{id}:
    get:
      tags:
        - "company"
      summary: "Find company by ID"
      operationId: "getCompanyById"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "X-Forwarded-For"
          type: "string"
          required: true      
        - in: "header"
          name: "Authorization"
          type: "string"
          required: true
        - name: "id"
          in: "path"
          required: true
          type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Company"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not found"
        "500":
          description: "Server error"
    put:
      tags:
        - "company"
      summary: "Update an existing company"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          required: true
        - name: "id"
          in: "path"
          description: "Company id to update"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Company object that needs to be updated"
          required: true
          schema:
            $ref: "#/definitions/Company"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Company"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not found"
        "500":
          description: "Server error"

    delete:
      tags:
        - "company"
      summary: "Deletes a company"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "X-Forwarded-For"
          type: "string"
          required: true      
        - in: "header"
          name: "Authorization"
          type: "string"
          required: true
        - name: "id"
          in: "path"
          description: "Company id to delete"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not found"
        "500":
          description: "Server error"

definitions:
  Company:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 1
      name:
        type: "string"
        example: "Mycompany"
      code:
        type: "string"
        example: "QYTD-1"
      country:
        type: "string"
        example: "United States"
      website:
        type: "string"
        example: "http://mycompany.com"
      phone:
        type: "string"
        example: "+37067934567"

  CreateCompanyRequest:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Mycompany"
      code:
        type: "string"
        example: "QYTD-1"
      country:
        type: "string"
        example: "United States"
      website:
        type: "string"
        example: "http://mycompany.com"
      phone:
        type: "string"
        example: "+37067934567"

  CompanyListResponse:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/Company"
      meta:
        type: "object"
        properties:
          pages:
            type: "integer"
            example: 1
          total:
            type: "integer"
            example: 1
  Login:
    type: object
    properties:
      user:
        type: "string"
        example: "user"
      pass:
        type: "string"
        example: "pass"

  LoginResponse:
    type: object
    properties:
      token:
        type: "string"
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IiIsImV4cCI6MTY2NDM1NzA1Nn0.y_gMc1_eODJpzYLs255S49GmXNip3hyUv0f3Ys5Ymgc"

